version: '3.8'

services:
  nexus-node:
    build: .
    container_name: nexus-node
    network_mode: host
    restart: unless-stopped
    environment:
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - NODE_ID=${NODE_ID}
    volumes:
      - ${HOME}/.nexus:/root/.nexus
      - /etc/resolv.conf:/etc/resolv.conf:ro
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    command: start --node-id ${NODE_ID}
    healthcheck:
      test: ["CMD", "curl", "-f", "https://production.orchestrator.nexus.xyz/v3/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nexus-interactive:
    build: .
    container_name: nexus-interactive
    network_mode: host
    profiles:
      - interactive
    environment:
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - NODE_ID=${NODE_ID}
    volumes:
      - ${HOME}/.nexus:/root/.nexus
      - /etc/resolv.conf:/etc/resolv.conf:ro
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    command: -c "
      echo '→ Health-check orchestrator:' &&
      curl -sS -w ' %{http_code}\\n' https://production.orchestrator.nexus.xyz/v3/health &&
      sleep 3 &&
      echo '→ Ping orchestrator:' &&
      ping -c3 production.orchestrator.nexus.xyz &&
      sleep 3 &&
      echo '→ Isi /root/.nexus:' &&
      ls -l /root/.nexus &&
      sleep 3 &&
      exec nexus-network start --node-id ${NODE_ID}
      "
